---
- name: Configure kernel modules
  block:
    - name: Load required kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop: "{{ kernel_modules }}"

    - name: Persist kernel modules
      ansible.builtin.template:
        src: modules-load.conf.j2
        dest: /etc/modules-load.d/kubernetes.conf
        owner: root
        group: root
        mode: "0644"
