---
- name: Disable swap
  block:
    - name: Check for active swap
      ansible.builtin.command: swapon --show --noheadings
      register: common_swap_status
      changed_when: false

    - name: Disable swap if active
      ansible.builtin.command: swapoff -a
      when: common_swap_status.stdout != ""
      changed_when: common_swap_status.stdout != ""

    - name: Comment out swap entry in /etc/fstab
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: "^(.*\\sswap\\s+.*)$"
        replace: "# \\1"
