[control]
server ansible_host=192.168.122.26

[workers]
node0 ansible_host=192.168.122.65
node1 ansible_host=192.168.122.11

[kubernetes:children]
control
workers

[kubernetes:vars]
ansible_user=root
#ansible_become=true
#ansible_become_method=sudo
#ansible_ssh_private_key_file=~/.ssh/devops2026